# -------------------------
# 1. Build Stage
# -------------------------
FROM node:20 AS build

WORKDIR /app

# Copy only package files first (better caching)
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy full source
COPY . .

# Build argument (Vite env)
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

# Build React app
RUN npm run build

# =========================
# PRODUCTION STAGE
# =========================
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
