server:
  port: 8082

  servlet:
    context-path: /product-mgmt
    
spring:
  application:
    name: product-mgmt

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #url: ${MYSQL_URL}
    #username: ${MYSQL_USERNAME}
    #password: ${MYSQL_PASSWORD}

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  data:
    cassandra:
      contact-points: cassandra
      port: 9042
      keyspace-name: main_db
      local-datacenter: dc1
      username: cassandra
      password: cassandra
      schema-action: none

eureka:
  client:
    register-with-eureka: true       # restister to eureka
    fetch-registry: true    
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
      #defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}   
      
##--------- fien properties ---------

user-mgmt:
  contextPath: "/user-mgmt"
  url: "http://127.0.0.1:8081"

product-mgmt:
  contextPath: "/product-mgmt"
  url: "http://127.0.0.1:8082"

security:
  contextPath: "/security"
  url: "http://127.0.0.1:8084"

  ## ----------- SECURITY PROPERTIES -------
  jwt:
    secret: bXlTdXBlclNlY3VyZUhTNTEyS2V5VGhhdElzQXRMZWFzdDY0Qnl0ZXNMb25nRm9yU2VjdXJlSldUVG9rZW5TaWduaW5nMTIzNDU2
    access-ttl-seconds: 36000
    refresh-ttl-seconds: 86400
    issuer: saurabh.com
  