server:
  port: 8082

  servlet:
    context-path: /product-mgmt
    
spring:
  application:
    name: product-mgmt

  data:
    cassandra:
      contact-points: ${CASSANDRA_CONTACTPOINTS}
      port: 9042
      keyspace-name: ${CASSANDRA_KEYSPACE}
      local-datacenter: ${CASSANDRA_LOCALDATACENTER}
      username: ${CASSANDRA_USER}
      password: ${CASSANDRA_PASSWORD}
      schema-action: create_if_not_exists

eureka:
  client:
    register-with-eureka: true       # restister to eureka
    fetch-registry: true    
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}   
      
##--------- fien properties ---------

user:
  contextPath: "/user"
  url: "http://user-mgmt:8081"

product:
  contextPath: "/product"
  url: "http://product-mgmt:8082"

  