server:
  port: 8082
  servlet:
    context-path: /product-mgmt
    
spring:
  application:
    name: product-mgmt

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  data:
    cassandra:
      contact-points: ${CASSANDRA_CONTACTPOINTS}
      port: 9042
      keyspace-name: ${CASSANDRA_KEYSPACE}
      local-datacenter: ${CASSANDRA_LOCALDATACENTER}
      username: ${CASSANDRA_USER}
      password: ${CASSANDRA_PASSWORD}
      schema-action: create_if_not_exists

eureka:
  client:
    register-with-eureka: true       # restister to eureka
    fetch-registry: true    
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}   
      
##--------- fien properties ---------

user:
  contextPath: "/user-mgmt"
  url: "http://127.0.0.1:8081"

product:
  contextPath: "/product-mgmt"
  url: "http://127.0.0.1:8082"

security:
  contextPath: "/security"
  url: "http://127.0.0.1:8084"

  ## ----------- SECURITY PROPERTIES -------
  jwt:
    secret: bXlTdXBlclNlY3VyZUhTNTEyS2V5VGhhdElzQXRMZWFzdDY0Qnl0ZXNMb25nRm9yU2VjdXJlSldUVG9rZW5TaWduaW5nMTIzNDU2
    access-ttl-seconds: 36000
    refresh-ttl-seconds: 86400
    issuer: saurabh.com